export default [
    {
      bg: '#4A9A3D',
      color: '#3F5B98',
      category: 'Manage House Applicance',
      cardicon: 'plug',
      subCategories: ['1', '2', '3', '4'],
    },
    {
      bg: '#4A9A3D',
      color: '#FCBE4A',
      category: 'My Profile',
      cardicon: 'plug',
      subCategories: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
      ],
    },
    {
      bg: '#FECBCA',
      color: '#FD5963',
      category: 'Untitled Text1',
      cardicon: 'plug',
      subCategories: ['Untitled Text11', 'Untitled Text12', 'Untitled Text13', 'Untitled Text14'],
    },
    {
      bg: '#193B8C',
      color: '#FECBCD',
      category: 'Untitled Text2',
      cardicon: 'plug',
      subCategories: [
        'Untitled Text21',
        'Untitled Text22',
        'Untitled Text23',
        'Untitled Text24',
        'Untitled Text25',
        'Untitled Text26',
        'Untitled Text27',
        'Untitled Text28',
        'Untitled Text29',
        'Untitled Text20',
      ],
    },
    {
      bg: '#FDBD50',
      color: '#F5F5EB',
      category: 'Untitled Text3',
      cardicon: 'plug',
      subCategories: [
        'Untitled Text31',
        'Untitled Text32',
        'Untitled Text33',
        'Untitled Text34',
        'Untitled Text35',
        'Untitled Text36',
        'Untitled Text37',
      ],
    },
  ];