export default [
    {
      bg: '#4A9A3D',
      color: '#3F5B98',
      category: 'Application Settings',
      cardicon: 'cog',
      subCategories: [
        'Application Reset',
        'Configuration Reset',
        'Dark Mode',
        'Untitled Text004',
    ],
    },
    {
      bg: '#4A9A3D',
      color: '#FCBE4A',
      category: 'Manage House Applicance',
      cardicon: 'plug',
      subCategories: [
        'Untitled Text01',
        /**'Untitled Text02',
        'Untitled Text03',
        'Untitled Text04',
        'Untitled Text05',
        'Untitled Text06',
        'Untitled Text07',
        'Untitled Text08',*/
      ],
    },
    {
      bg: '#FECBCA',
      color: '#FD5963',
      category: 'Set Location and Date',
      cardicon: 'map-marker-alt',
      subCategories: [
        'Set My Location',
        'Set My Time',
        'Set My Weather',
        'Untitled Text14',
      ],
    },
    {
      bg: '#193B8C',
      color: '#FECBCD',
      category: 'Untitled Text2',
      cardicon: 'futbol',
      subCategories: [
        'Untitled Text21',
        'Untitled Text22',
        'Untitled Text23',
        'Untitled Text24',
        'Untitled Text25',
        'Untitled Text26',
        'Untitled Text27',
        'Untitled Text28',
        'Untitled Text29',
        'Untitled Text20',
      ],
    },
    {
      bg: '#FDBD50',
      color: '#F5F5EB',
      category: 'Untitled Text3',
      cardicon: 'font',
      subCategories: [
        'Untitled Text31',
        'Untitled Text32',
        'Untitled Text33',
        'Untitled Text34',
        'Untitled Text35',
        'Untitled Text36',
        'Untitled Text37',
      ],
    },
  ];